#!/usr/bin/env bash
#code that displays numbers

for y in {1..100}
do
  if (( y % 3 == 0 && y % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( y % 3 == 0 ))
  then
    echo "Fizz"
  elif (( y % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$y"
  fi
done
